#!/usr/bin/env sh
set -eu

NAME="${SPOTIFY_NAME:-Toune-o-matic}"
BITRATE="${SPOTIFY_BITRATE:-320}"
CONF="/etc/raspotify/conf"

cat > "$CONF" <<EOF
# Generated by Toune-o-matic
DEVICE_NAME="$NAME"
BITRATE="$BITRATE"
# OPTIONS="--backend alsa --device hw:1,0"
EOF

if systemctl list-unit-files | grep -q "^raspotify.service"; then
  systemctl restart raspotify || true
fi
echo "written"
